version: "3.7"
# env_file:
#     - path: ./.env
services:
    mysqldb:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        # container_image: mysql-container
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./database/:var/lib/mysql
        restart: always
        ports:
            - "3308:3308"
