version: "3.7"
services:
    database:
        image: mysql
        container_name: memorygame-db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        restart: always
        env_file:
            - .env
        ports:
            - "3308:3308"
        volumes:
            - ./database:/docker-entrypoint-initdb.d/
